version: "3.9"

services:
  db:
    image: mongo
    container_name: babel_mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  www:
    build: ./client
    ports:
      - 8989:80

